# -*- coding: utf-8 -*-
"""bruteforce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DpIWw4a8GQcGjEvlrkVqa8lOomeSRW0f
"""

import time
import matplotlib.pyplot as plt

alfabeto = "abcdefghijklmnopqrstuvwxyz0123456789"

resultados = []
intentos = 0

def fuerza_bruta(contrasena, intento_actual):
    global intentos


    if len(intento_actual) == len(contrasena):
        intentos += 1
        if intento_actual == contrasena:
            return True
        else:
            return False


    for caracter in alfabeto:
        if fuerza_bruta(contrasena, intento_actual + caracter):
            return True

    return False

contrasenas_prueba = ["a", "b3", "cat"]

for contrasena in contrasenas_prueba:
    intentos = 0
    inicio = time.time()

    encontrada = fuerza_bruta(contrasena, "")

    fin = time.time()
    tiempo_total = fin - inicio

    if encontrada:
        print("Contraseña encontrada:", contrasena)
        print("Longitud:", len(contrasena))
        print("Intentos realizados:", intentos)
        print("Tiempo:", tiempo_total, "segundos")
        print("-" * 40)

        resultados.append((len(contrasena), intentos, tiempo_total))
    else:
        print("No se encontró la contraseña")
        print("-" * 40)

print("\nResumen:")
print("Longitud | Intentos | Tiempo")

for dato in resultados:
    print(dato[0], "        ", dato[1], "        ", dato[2])


longitudes = [dato[0] for dato in resultados]
tiempos = [dato[2] for dato in resultados]

plt.plot(longitudes, tiempos, marker="o")
plt.title("Tiempo vs Longitud de la contraseña")
plt.xlabel("Cantidad de caracteres")
plt.ylabel("Tiempo (segundos)")
plt.grid(True)
plt.show()