# -*- coding: utf-8 -*-
"""bruteforce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DpIWw4a8GQcGjEvlrkVqa8lOomeSRW0f
"""

import time

contrasena = "kpi"
alfabeto = "abcdefghijklmnopqrstuvwxyz1234567890"

intentos = 0
encontrada = False

incio = time.time()

for i in alfabeto:
    intento = i
    intentos += 1

    if intento == contrasena:
        print("La contrasena fue encontrada!", intento)
        encontrada = True
        break

for i in alfabeto:
    if encontrada == True:
        break

    for j in alfabeto:
        intento = i + j
        intentos += 1

        if intento == contrasena:
            print("La contrasena fue encontrada", intento)
            encontrada = True
            break
for i in alfabeto:
    if encontrada == True:
        break

    for j in alfabeto:
        if encontrada == True:
            break

        for k in alfabeto:
            intento = i + j + k
            intentos += 1

            if intento == contrasena:
                print("La contrasena fue encontrada:", intento)
                encontrada = True
                break

tiempo = time.time() - incio

print("El tiempo fue de:", tiempo)
print("Los intentos fueron:", intentos)